### ISSUE TITLE
Carthage Does Not Build

### ISSUE THREAD

**Issue by bpillon** [bahlo/SwiftGif#15]
adding the following to my Cartfile
    github "bahlo/SwiftGif"

results is the following:

    *** Skipped building SwiftGif due to the error:
    Dependency "SwiftGif" has no shared framework schemes for any of the platforms: iOS

**Comment by bahlo** [comment]
Hey, thanks for letting me know, I will look into it!

**Comment by bahlo** [comment]
Okay, so this bug is known and now handled in #17, thanks again for the info.
