### ISSUE TITLE
Memory leak after exiting view controller

### ISSUE THREAD

**Issue by digitalartworks** [bahlo/SwiftGif#21]
Oh, sorry, I just confound Your lib with another :) Anyway I was using Your lib, but it is memory inefficient. Better way is to allocate i.e. 5 frames in memory as cache and prepare another in runtime.

Good luck!

**Comment by bahlo** [comment]
Thank you for that information! :+1:

Maybe it would make sense to create a `destroy()`-Method to call on exit, I'll think check this.

**Comment by bahlo** [comment]
Closed as duplicate of #6.
