### ISSUE TITLE
Crash when gif from document directory.

### ISSUE THREAD

**Issue by AlbertSwift** [bahlo/SwiftGif#28]
i have download the list of gif from server into my document directory.
now when i m going to display it crash.

mycode:
let imageData = NSData(contentsOfURL: NSURL(fileURLWithPath: dataPath))
        let advTimeGif = UIImage.gifWithData(imageData!)

Crash at here::
var delayObject: AnyObject = unsafeBitCast(
            CFDictionaryGetValue(gifProperties,
                unsafeAddressOf(kCGImagePropertyGIFUnclampedDelayTime)),
            AnyObject.self)

**Comment by bahlo** [comment]
Are you still having this issue? 
If yes, can you try the new `v1.6.1` version and check if the problem persists? 

We removed the `unsafeAddressOf` call, so hopefully this bug is fixed. If not, feel free to re-open! 🍻
