### ISSUE TITLE
Stop animating when the image is resized.

### ISSUE THREAD

**Issue by lorenzoferrante** [bahlo/SwiftGif#31]
Hi, the gif is animating properly but when I try to resize the image to fit the screen width, the gif is not animating. Here's the code:

         /* IMAGEVIEW */
        var silvester: UIImage = UIImage.gifWithName("image")!

        let screenW: CGFloat = UIScreen.mainScreen().bounds.size.width
        let imageH: CGFloat = screenW / 1.3
        let sizeRight : CGSize = CGSize(width: screenW, height: imageH)
        silvester = scaleUIImageToSize(silvester, size: sizeRight)
        
        bgImage = UIImageView(image: silvester)
        self.view.addSubview(bgImage!)
        
        /* SCROLLVIEW */
        self.scrollView = UIScrollView(frame: view.bounds)
        self.scrollView.backgroundColor = UIColor.blackColor()
        scrollView.contentSize = bgImage.bounds.size
        scrollView.autoresizingMask = UIViewAutoresizing.FlexibleWidth
        scrollView.autoresizingMask = UIViewAutoresizing.FlexibleHeight
        
        scrollView.addSubview(bgImage)
        view.addSubview(scrollView)
        
        scrollView.delegate = self

And here is the function I use to scale the UIImage:

        func scaleUIImageToSize(let image: UIImage, let size: CGSize) -> UIImage {
             let hasAlpha = false
             let scale: CGFloat = 0.0 // Automatically use scale factor of main screen
        
             UIGraphicsBeginImageContextWithOptions(size, !hasAlpha, scale)
             image.drawInRect(CGRect(origin: CGPointZero, size: size))
        
             let scaledImage = UIGraphicsGetImageFromCurrentImageContext()
             UIGraphicsEndImageContext()
        
            return scaledImage
       }

What's the problem? 
Thanks.

**Comment by bahlo** [comment]
Hey, did you try embedding it in a `UIImageView` and scaling this?

**Comment by bahlo** [comment]
Closing for now, feel free to reopen.

**Comment by darthbatman** [comment]
embedding in a `UIImageView` and scaling does not solve this issue
