### ISSUE TITLE
Update to swift3?

### ISSUE THREAD

**Issue by petaire92** [bahlo/SwiftGif#35]
Hey,

Just wanted to know if you're planning to update it for Swift3 or if it's abandonned ! So I can look for another third party option ! It would be a shame, it's the more practical and the lightest one !

**Comment by bahlo** [comment]
Hey, Swift 3 support is planned, I'm just not having the time at the moment, will try to do it this week 💪

**Comment by petaire92** [comment]
Great ! Let us know !

**Comment by bahlo** [comment]
Merged in [v1.6-beta.1](https://github.com/bahlo/SwiftGif/releases/tag/v1.6-beta.1) (soon to be master, when Swift 3 is released). 😁
