### ISSUE TITLE
Does not work within extensions

### ISSUE THREAD

**Issue by geppelt** [bahlo/SwiftGif#36]
Pretty straight forward: does not work within extensions (eg Keyboard).

**Comment by bahlo** [comment]
Which version did you use? What doesn't work? Is there an error message or just no animation?

**Comment by geppelt** [comment]
Version? I am using XCode 7.3 with iOS 9.3.5.

Original it would not recognize the extensions, but I got that working by implementing it straight into the ViewController's Swift file. It use to throw the error "Image 'XXX' does not excists", which was wrong, but now the keyboard just fails to initalize with throwing any error.

**Comment by bahlo** [comment]
Hey @geppelt, are you still having this issue? 

I would recommend to get `UIImage("yourfile.gif")` to work (without animation) from your keyboard and replacing it with the `SwiftGif` code after that worked.

Feel free to re-open this if the issue persists.
