### ISSUE TITLE
Errors on Xcode 8 GM

### ISSUE THREAD

**Issue by chaitanya-ramji** [bahlo/SwiftGif#38]
Hey,
There are couple of errors while building on Xcode 8 GM. Could you please fix it and patch an update?

Thanks :)

**Comment by bahlo** [comment]
Hey @chaitanya-ramji, did you check out the v1.6-beta.1?

**Comment by chaitanya-ramji** [comment]
Yep, I used the file from that branch. I'll give it another try in a fresh XC project.
Cheers :)

**Comment by bahlo** [comment]
Hey @chaitanya-ramji, will close this now - feel free to reopen if this issue persists. 💯
