### ISSUE TITLE
How to pause temporarily the gif?

### ISSUE THREAD

**Issue by peihsendoyle** [bahlo/SwiftGif#41]
Hi Bahlo, I've just took a look on your library. Everything works amazingly, but I am in stuck with a problem. How to pause temporarily the gif? I want pause and resume it for some reason (like music play, pause...)

Thanks very much and wait for your reply.

**Comment by AlexInTheMountains** [comment]
I am also curious as how to pause/stop the animation?

**Comment by bahlo** [comment]
Hey guys, you can use [`stopAnimating()`](https://developer.apple.com/reference/uikit/uiimageview/1621057-stopanimating) from `UIImageView` to stop the animation. 

Feel free to re-open if that doesn't answer your question 👍

**Comment by AlexInTheMountains** [comment]
Hi, stopAnimating() is not working for me? I use Swift 3 on xcode 8. So basically the stopAnimating call does have no effect and gif continues to loop and loop.

**Comment by bahlo** [comment]
Hey @AlexInTheMountains, did you configure the `UIImageView` like described [here](https://github.com/bahlo/SwiftGif/wiki/Extended-use)? I just tried it and it works for me.

**Comment by Maryom** [comment]
Hey @bahlo Thanks for this great repo.

I have same issue so I tried the following:

```
            // CAKeyframeAnimation.values are expected to be CGImageRef,
            // so we take the values from the UIImage images
            var values = [CGImage]()
            for image in jeremyGif!.images! {
                values.append(image.cgImage!)
            }
            
            // Create animation and set SwiftGif values and duration
            let animation = CAKeyframeAnimation(keyPath: "contents")
            animation.calculationMode = CAAnimationCalculationMode.discrete
            animation.duration = jeremyGif!.duration
            animation.values = values
            // Set the repeat count
            animation.repeatCount = 1
            // Other stuff
            animation.isRemovedOnCompletion = false
            animation.fillMode = CAMediaTimingFillMode.forwards
            // Set the delegate
            animation.delegate = self
            gifCounter.layer.add(animation, forKey: "animation")            
```

I can stop the gif by running `stopAnimating()` but the problem it starts from the beginning. I need to pause the gif not to stop it, then when I play it after pause I need it to continue from where it stops not to start from beginning.

Any idea how to do it?
