### ISSUE TITLE
1.6 isn't listed in the CocoaPods specs

### ISSUE THREAD

**Issue by Danm72** [bahlo/SwiftGif#43]
Hey guys,

I'm new to ios development, but using 1.6 in my podfile didn't work so I checked the specs repo to see if its listed and the last spec listed is 1.5.3

https://github.com/CocoaPods/Specs/tree/master/Specs/SwiftGifOrigin

**Comment by bahlo** [comment]
You are right, I just pushed `v1.6.1` to CocoaPods, using that version should work now. Feel free to reopen if this problem persists.
