### ISSUE TITLE
add to cocoapods

### ISSUE THREAD

**Issue by mackuba** [bahlo/SwiftGif#5]
Hi,

it would be nice to have the library in CocoaPods (right now I've added it using Peru https://github.com/buildinspace/peru).

BTW, I love the demo gif in the readme ;)

**Comment by bahlo** [comment]
Good idea, thanks for the suggestion. Unfortunately I have a lot on my plate right now, so it may last a few weeks. 

But if you want to open a PR, you're very welcome! :+1:

PS: Gifs are great. :grin:

**Comment by chrischristo** [comment]
hey how would I add a gif image by name from my images.xcassets?

**Comment by SamBuydens** [comment]
I've imported the files and it works just fine with the demo gifs provided but when I load in a 3.9mb 640x400 gif the gif lags and the memory of the device (running in simulator) reaches 223mb, this seems exceedingly high. 

Is there a limit for the gif that I'm using that I should take in account?
