### ISSUE TITLE
Image loaded but not animating

### ISSUE THREAD

**Issue by sine27** [bahlo/SwiftGif#52]
I programmatically added a gif in a stackview, however, the image is not animating

"display_url" = "pic.twitter.com/PD4fxB83OI";
"expanded_url" = "https://twitter.com/MarcAnthony/status/836026935813746688/photo/1";
"media_url" = "http://pbs.twimg.com/tweet_video_thumb/C5oqDsuXQAAEEcm.jpg";

**Comment by fukemy** [comment]
hi, how did u solve it?
