### ISSUE TITLE
Can a gif be loaded from an asset catalog?

### ISSUE THREAD

**Issue by neilyoung** [bahlo/SwiftGif#66]
Getting 

`SwiftGif: This image named "njoy" does not exist`

while trying

**Comment by Aaron-Thomas** [comment]
Same thing happened to me. Xcode now doesn't recognise gif files in the .xcassets folder. To solve this i made a new group called 'Gif', outside of the .xcassets folder and added my .gif files to this. Then called it in the same way; e.g. myImageView.image = UIImage.gif(name: "mygif") Worked for me!

**Comment by xAlien95** [comment]
You could extend your `UIImage` class:

```swift
extension UIImage {
    public class func gif(asset: String) -> UIImage? {
        if let asset = NSDataAsset(name: asset) {
            return UIImage.gif(data: asset.data)
        }
        return nil
    }
}
```

You'll be able to load GIFs from assets based on their names using

```swift
imageView.image = UIImage.gif(asset: "njoy")
```

**Comment by bahlo** [comment]
#68 is merged, closing. Feel free to open if the issue persists.

**Comment by bitops** [comment]
@bahlo I am using version 1.6.1 and encountered this error. I looked in the source code that CocoaPods pulled down and I don't see the code that allows you to look up the image as an asset. Is the code not released or am I doing something wrong? Thanks so much!

By putting my images in a folder outside of the asset folder I was able to load the image just fine.

**Comment by AdiAyyakad** [comment]
Seconded. Can a version please be released with this PR in it?
